name: Deploy Function App  
  
on:  
  workflow_dispatch:  
    inputs:  
      branch:  
        description: 'The branch to deploy'  
        required: true  
        default: 'ST'  
  
env:  
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # Path to your web app project  
  DOTNET_VERSION: '8.0.x'             # .NET version to use  
  
jobs:  
  build-and-deploy:  
    runs-on: windows-latest  
    permissions:  
      id-token: write # Required for requesting the JWT  
  
    steps:  
      - name: Checkout Selected Branch  
        uses: actions/checkout@v4  
        with:  
          ref: ${{ github.event.inputs.branch }}  
  
      - name: Setup .NET ${{ env.DOTNET_VERSION }} Environment  
        uses: actions/setup-dotnet@v3  
        with:  
          dotnet-version: ${{ env.DOTNET_VERSION }}  
  
      - name: Resolve Project Dependencies Using dotnet  
        shell: pwsh  
        run: |  
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'  
          dotnet build --configuration Release --output ./output  
          popd  
        
      - name: Login to Azure  
        uses: azure/login@v1  
        with:  
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}  
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}  
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}  
  
      - name: Run Azure Functions Action  
        uses: Azure/functions-action@v1  
        id: fa  
        with:  
          app-name: 'Promotionapp20250101233608'  
          slot-name: 'Production'  
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'  
